name: Playwright Tests
on:
  workflow_dispatch:  # Manual trigger
    inputs:
      branch:
        description: 'Branch to test against' 
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - master
      environment:
        description: 'Environment to test'
        required: false
        default: 'production'
        type: string

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}  # Use selected branch
        
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
      
    - name: Run Playwright tests
      run: |
        npx playwright test \
          --workers=2 \
          --retries=2 \
          --timeout=60000 \
          --project=chromium \
          --headed \
      env: 
        E2E_BASE_URL: https://kuroiel.github.io/Doro-clicker/
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30