name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test against' 
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - master

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium
        npx playwright install-deps
      
    - name: Run Playwright tests
      run: |
        npx playwright test \
          --workers=1 \
          --retries=2 \
          --timeout=60000 \
          --project=chromium \
          --config=playwright.config.js
      env: 
        E2E_BASE_URL: https://kuroiel.github.io/Doro-clicker/
        PLAYWRIGHT_DISABLE_FORCED_COLORS: 1
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
        DEBUG: playwright:*
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30