name: Playwright Tests

on:
  # This section enables manual runs from the Actions tab.
  workflow_dispatch:
    inputs:
      # The branch input is now correctly used in the checkout step below.
      branch:
        description: "Branch to test against"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - master
      # FIXED: Renamed 'environment' to 'target_environment' to avoid keyword conflict.
      target_environment:
        description: "Environment to test"
        required: false
        default: "production"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      # FIXED: This step now uses the 'branch' input you select in the UI.
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # This step is a good check to ensure the deployment is live before testing.
      - name: Verify Exact Page URL is accessible
        run: |
          TEST_URL="https://kuroiel.github.io/Doro-clicker/"
          echo "Testing URL: $TEST_URL"
          if ! curl -sSf "$TEST_URL" >/dev/null 2>&1; then
            echo "::error::Failed to access $TEST_URL"
            curl -v "$TEST_URL" || true
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test --workers=1 --project=chromium
        env:
          # Note: The 'target_environment' input is not used here, but you could
          # add logic to change the BASE_URL based on its value if you had
          # different environments (e.g., staging, production).
          E2E_BASE_URL: https://kuroiel.github.io/Doro-clicker/
          PLAYWRIGHT_TEST_TIMEOUT: 30000

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
