name: Playwright CI Pipeline

on:
  # Trigger 1: Runs automatically on any push to the 'main' branch.
  push:
    branches: [main]

  # Trigger 2: Runs automatically on any pull request that targets the 'main' branch.
  pull_request:
    branches: [main]

  # Trigger 3: Allows you to manually run the workflow on the 'main' branch at any time.
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Verify Exact Page URL is accessible
        run: |
          TEST_URL="https://kuroiel.github.io/Doro-clicker/"
          echo "Testing URL: $TEST_URL"
          if ! curl -sSf "$TEST_URL" >/dev/null 2>&1; then
            echo "::error::Failed to access $TEST_URL"
            curl -v "$TEST_URL" || true
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test --workers=1 --project=chromium
        env:
          E2E_BASE_URL: https://kuroiel.github.io/Doro-clicker/
          PLAYWRIGHT_TEST_TIMEOUT: 30000

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
