name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test against'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - master

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Simplified deployment check
    - name: Verify GitHub Pages Availability
      run: |
        if ! curl -s -f https://kuroiel.github.io/Doro-clicker/ > /dev/null; then
          echo "GitHub Pages not available"
          exit 1
        fi
        
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium
      
    - name: Run Playwright tests
      run: npx playwright test --workers=1 --project=chromium
      env: 
        E2E_BASE_URL: https://kuroiel.github.io/Doro-clicker/
        PLAYWRIGHT_TEST_TIMEOUT: 60000
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30