name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 15  # Reduced from 60 since we'll optimize
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}        
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps chromium  # Only install Chromium
    - name: Check site availability
      run: |
        for i in {1..5}; do
          if curl -s -I $E2E_BASE_URL | grep "200 OK"; then
            echo "Site is available"
            exit 0
          fi
          echo "Attempt $i: Site not ready, retrying in 25s..."
          sleep 25
        done
        echo "Site did not become available"
        exit 1
      env: 
        E2E_BASE_URL: https://kuroiel.github.io/Doro-clicker/
    - name: Run Playwright tests
      run: |
        npx playwright test \
          --workers=2 \
          --retries=1 \
          --timeout=30000 \
          --project=chromium
      env: 
        E2E_BASE_URL: https://kuroiel.github.io/Doro-clicker/
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1  # Use already installed browser
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30