name: Unit Tests

on:
  # Trigger 1: Runs automatically on any push to the 'main' branch.
  push:
    branches: [main]

  # Trigger 2: Runs automatically on any pull request that targets the 'main' branch.
  pull_request:
    branches: [main]

  # Trigger 3: Allows you to manually run the workflow.
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to test against"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - master

jobs:
  unit-tests:
    name: Run Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Cache Jest files
        uses: actions/cache@v3
        with:
          path: |
            **/.jest-cache
          key: ${{ runner.os }}-unit-jest-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npx jest unit --ci --coverage --reporters=default --reporters=jest-junit

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: unit-test-results
          path: |
            coverage/
            junit.xml
          retention-days: 7
