name: Unit Tests
on:
  workflow_dispatch:  
    inputs:
      branch:
        description: 'Branch to test against' 
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - master
      environment:
        description: 'Environment to test'
        required: false
        default: 'production'
        type: string

jobs:
  unit-tests:
    name: Run Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          **/.jest-cache
        key: ${{ runner.os }}-unit-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npx jest unit --ci --coverage --reporters=default --reporters=jest-junit

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: unit-test-results
        path: |
          coverage/
          junit.xml
        retention-days: 7